'use strict';
// v0.6의 8개 서비스와 ERP 후속관리 구조를 계승. v1.0은 홈·탐색 우선 프로토타입.
const paths={home:'M3 11 12 3l9 8M5 10v11h5v-7h4v7h5V10',checkup:'M9 4H5v17h14V4h-4M9 2h6v5H9zM8 12h8M8 16h5',program:'M4 6h16v15H4zM7 3v6M17 3v6M4 11h16M8 15h2M14 15h2',body:'M9 5a3 3 0 1 0 6 0 3 3 0 0 0-6 0M4 11l8-2 8 2M12 9v7M12 16l-5 6M12 16l5 6',mind:'M12 21S2 15 2 8a5 5 0 0 1 10-1 5 5 0 0 1 10 1c0 7-10 13-10 13',walk:'M5 5h4l2 7 8 4c2 1 3 2 2 4H3v-6l2-9M11 12l-3 3',culture:'M12 3v4M12 17v4M3 12h4M17 12h4M5 5l3 3M16 16l3 3M5 19l3-3M16 8l3-3M9 12a3 3 0 1 0 6 0 3 3 0 0 0-6 0',ai:'M4 6h16v13H4zM12 2v4M8 11h1M15 11h1M8 15h8M2 10v5M22 10v5',sos:'M12 3 2 21h20L12 3M12 9v5M12 18h.01',manager:'M3 3v18h18M7 16v-5M12 16V7M17 16v-8',back:'M15 5l-7 7 7 7',next:'M9 5l7 7-7 7',leaf:'M4 20c0-10 8-16 17-16 0 9-6 17-14 15M5 19l10-10',org:'M3 21V8h8v13M11 21V3h10v18M6 11h2M6 15h2M14 7h3M14 11h3M14 15h3',moon:'M21 14A9 9 0 0 1 10 3a9 9 0 1 0 11 11',heart:'M12 21S2 15 2 8a5 5 0 0 1 10-1 5 5 0 0 1 10 1c0 7-10 13-10 13',check:'M5 12l4 4L19 6'};
const icon=k=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[k]||paths.leaf}"/></svg>`;
const services=[['checkup','건강검진','blue'],['program','프로그램','gold'],['body','몸 건강','blue'],['mind','마음건강','pink'],['walk','건강챌린지',''],['culture','건강문화','gold'],['ai','AI 도우미',''],['sos','응급·SOS','pink']];
const names=Object.fromEntries(services.map(x=>[x[0],x[1]]));
const view=document.getElementById('view'),nav=document.getElementById('nav');
let org='',page='home',part='목·어깨',remaining=180,timer=null,mission=false,careStep=0,dashTab='건강검진';
let body;
const ORGANIZATIONS=['본사','국토정보교육원','공간정보연구원','서울경기북부지역본부','부산울산지역본부','인천경기남부지역본부','강원지역본부','충북지역본부','대전세종충남지역본부','전북지역본부','전남광주지역본부','대구경북지역본부','경남지역본부','제주지역본부'];
const orgSelect=()=>`<select id="org" aria-label="소속 선택"><option value="">소속 선택</option>${ORGANIZATIONS.map(o=>`<option ${o===org?'selected':''}>${o}</option>`).join('')}</select>`;
const head=(title)=>`<div class="pagehead"><button class="back" data-back="1" aria-label="이전 화면으로 돌아가기">${icon('back')}</button><h1>${title}</h1></div>`;
const sample='<div class="sample">SAMPLE · 발표용 시나리오입니다. 실제 LX 운영자료·개인 건강정보가 아닙니다.</div>';
const card=(title,body)=>`<div class="card"><h3>${title}</h3><p class="small">${body}</p></div>`;
const homeQuotes=['잠깐 쉬고,<br>가볍게 움직여요','바쁜 하루에도,<br>나를 돌보는 시간','작은 실천으로,<br>건강한 일상을','오늘의 건강,<br>가까이에서 챙겨요','몸도 마음도,<br>잠깐 쉬어가요','건강한 습관,<br>하나씩 시작해요'];
let homeQuoteIndex=-1;
function pickHomeQuote(){let previous=homeQuoteIndex;try{if(previous<0)previous=Number(sessionStorage.getItem('lxhai-last-quote')??-1)}catch{}const choices=homeQuotes.map((_,i)=>i).filter(i=>i!==previous);homeQuoteIndex=choices[Math.floor(Math.random()*choices.length)];try{sessionStorage.setItem('lxhai-last-quote',String(homeQuoteIndex))}catch{}}
pickHomeQuote();
function home(){return `<div class="intro"><div><h1>내 손안의 건강</h1><div class="small" style="color:var(--sub)">LX인의 건강한 일상을 더 가깝게</div></div><div class="org">${orgSelect()}</div></div><section class="hero"><div class="copy"><div class="eyebrow">YOUR HEALTH PARTNER</div><h2>${homeQuotes[homeQuoteIndex]}</h2><button class="textbtn" data-go="ai">무엇을 도와드릴까요? ${icon('next')}</button></div><img src="assets/randy.png" alt="첨부된 AI 건강도우미 랜디"></section><div class="sectionhead"><h2>내 건강서비스</h2><span class="meta">필요할 때, 바로</span></div><div class="services">${services.map(([k,n,c])=>`<button class="service" data-go="${k}"><span class="iconbox ${c}">${icon(k)}</span>${n}</button>`).join('')}</div><section class="card"><div class="row"><h2>오늘의 작은 실천</h2><span class="badge">DEMO</span></div><div class="today"><div class="stat">${icon('walk')}<b>연동 전</b>오늘 걸음</div><button class="stat" style="border:0" data-go="body">${icon('body')}<b>3분 케어</b>몸 가볍게</button><button class="stat" style="border:0" data-go="mind">${icon('moon')}<b>잠깐 쉼</b>마음 편안하게</button></div></section><button class="banner" data-go="program"><span class="iconbox">${icon('program')}</span><div><strong>${org?org+'에서 함께하는 건강': '함께하는 건강프로그램'}</strong><span>${org?'전사 + 내 소속 프로그램 보기':'소속을 선택하고 참여활동을 찾아보세요'}</span></div>${icon('next')}</button><div class="foot">교육 발표용 프로토타입 · 실제 건강정보를 입력하지 마세요.</div><button class="managerlink" data-go="manager">보건관리자 화면 <span class="badge">DEMO</span></button>`}
function mind(){return head('마음건강')+`<section class="crisis-card"><h2>지금 많이 힘들다면</h2><p>혼자 견디지 않아도 돼요. 24시간 전화로 바로 이야기할 수 있어요.</p><div class="crisis-links"><a href="tel:109"><strong>109</strong><span>자살예방 상담전화 · 24시간</span></a><a href="tel:1577-0199"><strong>1577-0199</strong><span>정신건강위기 상담전화</span></a></div></section><section class="card eap-card" id="eap"><div class="row"><h2>EAP 심리상담 지원프로그램</h2><span class="tag">회사 지원</span></div><dl class="eap-facts"><div><dt>운영 기간</dt><dd>공고일 ~ 2026. 12. 4.(금)</dd></div><div><dt>대상</dt><dd>LX 및 LX 협력사 전 직원</dd></div><div><dt>횟수</dt><dd>1인 최대 5회기 이내</dd></div><div><dt>장소</dt><dd>협약상담센터 (자택 제외)</dd></div><div><dt>상담 내용</dt><dd>조직과 직무, 대인관계, 개인·가정문제 등</dd></div><div><dt>비용·비밀보장</dt><dd>회사 지원. 상담 내용은 근로복지기본법 제83조에 따라 소속기관 및 타인에게 비밀이 보장됩니다.</dd></div><div><dt>문의</dt><dd><a href="tel:15665228">1566-5228</a> · 카카오톡 채널 ‘EAP상담’ 검색</dd></div><div><dt>긴급 상담</dt><dd><a href="tel:0222610140">02-2261-0140</a> · 오아심스 로그인 화면 기준</dd></div></dl><p class="meta">예산 소진 시 조기 종료될 수 있음 · 예약 24시간 이내 취소·당일 불참 시 1회 차감</p><details class="eap-steps"><summary>처음 신청하는 방법</summary><ol><li>오아심스 웹사이트 또는 앱에 접속하고 소속회사명에 <strong>한국국토정보공사</strong>를 입력합니다.</li><li>처음이면 회원가입을 선택합니다. 안내 팝업 ‘예’ → ‘오아심스 가입’ → 약관 동의 → 본인인증 후 정보를 입력합니다.</li><li>로그인 후 안내에 따라 분석단위(연령대·거주지역·직급 등)를 입력합니다.</li><li>서비스 신청 → 상담 및 심리검사 신청 → ‘외부상담’을 선택하고 상담 분야·방법을 고릅니다.</li><li>상담동의서를 작성하고 사전검사(효과성 10문항, 개인·조직 영역 각 4문항)를 진행합니다.</li><li>지역별 상담센터를 선택하거나 ‘전문가 추천받기’에서 희망 일시·지역을 입력해 신청합니다.</li><li>신청 내역은 My Oasims &gt; 나의 상담에서 확인합니다.</li></ol><div class="notice">아이디·비밀번호 입력 시 공백이 없는지 확인하세요. 분실 시 로그인 화면에서 소속회사명을 입력한 뒤 ‘아이디 찾기/비밀번호 찾기’를 이용하세요.</div></details><div class="eap-actions"><a class="btn" href="https://oasims.com" target="_blank" rel="noopener">오아심스 바로가기</a><a class="btn secondary" href="assets/eap-2026.jpg" target="_blank" rel="noopener">원본 안내문 보기</a></div><p class="meta">개인 상담 내용과 신청 여부는 이 앱에 기록하거나 전송하지 않습니다.</p></section><button class="listbtn" data-micro="잠깐 호흡에 집중하기"><span class="iconbox blue">${icon('moon')}</span><div><h3>Micro-Care</h3><span class="small">호흡 · 감정정리 · 잠깐의 쉼</span></div>${icon('next')}</button><div id="mindresult"></div>`;}
function walk(){return head('건강챌린지')+`<p class="lead">걸음의 경쟁보다, 나에게 맞는 꾸준한 실천.</p><div class="card"><div class="row"><h3>오늘의 걸음</h3><span class="badge">연동 전</span></div><p>걸음 데이터가 연결되지 않았어요.</p><p class="meta">향후 건강앱 연계 검토</p></div><div class="card"><div class="row"><h3>나의 작은 미션</h3><span class="badge">DEMO</span></div><p class="small">잠깐 자리에서 일어나 쉬어가기</p><button class="btn ${mission?'secondary':''}" id="mission">${mission?'완료 취소':'실천 완료'}</button></div><div class="card"><div class="row"><span class="iconbox">${icon('leaf')}</span><div><h3>건강나무</h3><p class="small">${mission?'오늘의 실천으로 새싹이 자랐어요.':'작은 실천이 건강나무를 키워요.'}</p></div></div><div class="progress" style="margin-top:14px"><span style="width:${mission?100:0}%"></span></div><p class="meta">현재 화면 안에서만 체험하는 미션 예시</p></div>`;}
function culture(){return head('함께 만드는 건강문화')+sample+card('칭찬·감사','동료에게 전하는 따뜻한 응원. 감사와 칭찬을 나누는 공간으로 확장할 예정이에요.')+card('오늘의 힐링사진','풍경과 일상 속 작은 쉼을 함께 나눠요. 사진 게시·공감 기능은 후속 구현 예정입니다.')+`<button class="btn secondary" id="thanks">감사 예시 보기</button><div id="cultureresult"></div>`;}
function sos(){return head('응급·SOS')+`<div class="notice" style="background:#fff0f1;color:#a32f3f">응급상황에서는 119 신고와 신속한 대응을 우선하세요.</div><a class="emergency-call" href="tel:119">${icon('sos')}<span><strong>119 긴급신고</strong><small>전화 앱으로 바로 연결</small></span></a><div class="crisis-links sos-crisis"><a href="tel:109"><strong>109</strong><span>자살예방 상담전화 · 24시간</span></a><a href="tel:1577-0199"><strong>1577-0199</strong><span>정신건강위기 상담전화</span></a></div><div class="emergency-grid"><a class="emergency-tile lx" href="https://sos.lx.or.kr/" target="_blank" rel="noopener">${icon('sos')}<strong>LX SOS</strong><span>내 위치 신고 · 응급처치<br>근거리 응급시설</span></a><a class="emergency-tile aed" href="https://www.e-gen.or.kr/egen/search_aed.do" target="_blank" rel="noopener">${icon('heart')}<strong>AED 찾기</strong><span>E-Gen 공식 검색<br>주변 설치 위치 확인</span></a></div><div class="sectionhead"><h2>폭염·한파 건강관리</h2></div><div class="season-cards"><button class="season-card heat" data-climate-open="summer"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M5 5l2 2M17 17l2 2M5 19l2-2M17 7l2-2"/></svg><strong>온열질환</strong><span>더위에 대비해요</span><small>체감온도 · 예방 · 대응</small></button><button class="season-card cold" data-climate-open="winter"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2v20M3.34 7l17.32 10M3.34 17l17.32-10M9 3l3 3 3-3M9 21l3-3 3 3M3 10l4-1-1-4M21 14l-4 1 1 4M3 14l4 1-1 4M21 10l-4-1 1-4"/></svg><strong>한랭질환</strong><span>추위에 대비해요</span><small>체감온도 · 예방 · 대응</small></button></div><div id="sosresult"></div>`;}
function ai(){return head('AI 건강도우미')+`<div class="aiintro"><img src="assets/randy.png" alt="랜디"><div><h2>랜디에게 물어보세요</h2><p class="small">건강정보와 활동을 찾는<br>나의 서비스 길잡이</p></div></div><div class="notice">Navigator DEMO · 의료진단·치료를 제공하지 않아요. 현재는 미리 정한 질문의 메뉴 연결을 체험합니다.</div>${[['checkup','내게 맞는 검진기관을 찾고 싶어요'],['program','참여할 수 있는 프로그램이 있나요?'],['body','목·어깨 케어를 하고 싶어요'],['mind','마음이 지칠 때 도움이 필요해요'],['sos','응급상황에서 어디로 연결하나요?']].map(([k,t])=>`<button class="listbtn" data-ai="${k}">${t}</button>`).join('')}<div id="answer" aria-live="polite"></div>`;}
const flows=['이상징후·문의 접수','보건관리자 확인','필요한 건강평가','상담·후속관리'];
function manager(){return head('Health Intelligence')+`<div class="eyebrow">보건관리자 DASHBOARD · DEMO</div><p class="lead">조직 건강현황과 필요한 후속관리를 한곳에서.</p>`+sample+`<section class="dashboard"><div class="sectionhead"><h2>주요 건강현황</h2><span class="meta">실제 자료 미연결</span></div><div class="metrics">${['건강검진','생활습관','뇌심혈관 위험','근골격계','마음건강','건강증진 프로그램'].map(n=>`<div class="metric"><span class="small">${n}</span><b>—</b><span class="meta">데이터 미연결</span></div>`).join('')}</div><div class="sectionhead"><h2>확인부터 후속관리까지</h2></div><p class="small">ERP 건강상태 모니터링의 이상징후 또는 보건관리자 문의를 출발점으로 관리합니다.</p><div class="steps">${flows.map((s,i)=>`<div class="step ${i===careStep?'current':''}"><i>${i+1}</i><div><b>${s}</b><div class="meta">${['ERP 이상징후 / 보건관리자 문의','상태·상황 및 추가 확인정보 검토','뇌심혈관 발병위험도 등 필요한 평가','상담·연계·추적 확인'][i]}</div></div></div>`).join('')}</div><div class="card"><span class="tag">SAMPLE CASE · 개인정보 없음</span><h3 style="margin-top:10px">${flows[careStep]}</h3><p class="small">${['접수 경로를 확인하고 담당 보건관리자에게 연결합니다.','증상·작업상황·응급성 등을 보건관리자가 확인합니다.','필요한 평가를 선택합니다. AI가 위험도를 자동 판정하지 않습니다.','상담과 필요한 서비스 연계를 기록하고 후속 확인으로 연결합니다.'][careStep]}</p><div class="inline"><button class="btn secondary" id="care-reset">처음으로</button><button class="btn" id="care-next">${careStep===3?'시나리오 다시 보기':'다음 단계'}</button></div></div><h2 style="margin-top:20px">영역별 관리 보기</h2><div class="chips">${['건강검진','생활습관','뇌심혈관','근골격계','마음건강','프로그램'].map(t=>`<button class="chip ${dashTab===t?'active':''}" data-dash="${t}">${t}</button>`).join('')}</div>${card(dashTab,{'건강검진':'검진 현황·사후관리·상담 연계','생활습관':'흡연·신체활동 등 생활습관 집계','뇌심혈관':'필요한 발병위험도 평가·상담·추적관리','근골격계':'불편 증상·유해요인·예방활동 연계','마음건강':'EAP 등 집계자료 기반 이용현황·지원 연계','프로그램':'참여 현황·운영 결과·후속 개선'}[dashTab]+' · 데이터 미연결')}<p class="meta">실제 계정 권한 구분은 구현하지 않은 화면 전환 DEMO입니다. 특수건강진단은 포함하지 않습니다.</p></section>`;}
function fmt(n){return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
document.addEventListener('change',e=>{if(e.target.id==='org'){org=e.target.value;render()}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
if(b.dataset.part){part=b.dataset.part;render();return}if(b.dataset.dash){dashTab=b.dataset.dash;render();return}
if(b.dataset.program){const title=b.dataset.program;view.innerHTML=head('프로그램 안내')+sample+card(title,'참여대상·일정·신청방법이 들어갈 상세 화면입니다. 실제 모집이나 신청은 이루어지지 않습니다.')+'<button class="btn secondary" data-go="program">프로그램 목록으로</button>';return}
if(b.id==='search'){const r=document.getElementById('region').value,t=document.getElementById('type').value,x=document.getElementById('exam').value;const hs=hospitals.filter(h=>(r==='전체'||h.region===r)&&(t==='전체'||h.types.includes(t))&&(x==='전체'||h.exam===x));const el=document.getElementById('results');el.className='';el.innerHTML=hs.length?`<p class="small">SAMPLE 검색결과 · 실제 계약기관이 아닙니다.</p>`+hs.map(h=>`<div class="card"><h3>${h.name}</h3><p class="small">${h.region} · ${h.types.join(' / ')} · ${h.exam}</p><label class="small"><input type="checkbox" name="compare" value="${h.name}"> 비교에 담기</label></div>`).join('')+'<button class="btn secondary" id="compare">선택 기관 비교</button><div id="comparison"></div>':'<div class="empty">일치하는 SAMPLE 기관이 없습니다.<br>조건을 넓혀 다시 검색해보세요.</div>';return}
if(b.id==='compare'){const selected=[...document.querySelectorAll('[name=compare]:checked')].map(c=>hospitals.find(h=>h.name===c.value));document.getElementById('comparison').innerHTML=selected.length<2?'<div class="notice">비교할 기관을 2곳 이상 선택하세요.</div>':selected.map(h=>card(h.name,`${h.region}<br>유형: ${h.types.join(', ')}<br>관심검사: ${h.exam}<br>SAMPLE · 비용·예약정보 미연결`)).join('');return}
if(b.id==='start'){if(timer){clearInterval(timer);timer=null;render()}else{b.textContent='잠시 멈춤';timer=setInterval(()=>{remaining--;const el=document.getElementById('time');if(el)el.textContent=fmt(remaining);if(remaining<=0){clearInterval(timer);timer=null;document.getElementById('start').textContent='휴식 완료';document.getElementById('start').disabled=true;}},1000)}return}
if(b.id==='reset'){clearInterval(timer);timer=null;remaining=180;render();return}if(b.id==='mission'){mission=!mission;render();return}
if(b.dataset.micro){document.getElementById('mindresult').innerHTML=card(b.dataset.micro,b.dataset.micro.includes('EAP')?'EAP 이용 절차·접속 링크가 들어갈 영역입니다. 현재 상담 접수는 되지 않습니다.':'잠깐 화면에서 눈을 떼고, 편안한 자세로 쉬어가세요. 호흡·감정정리 콘텐츠는 전문가 검토 후 연결 예정입니다.');return}
if(b.id==='thanks'){document.getElementById('cultureresult').innerHTML=card('SAMPLE · 감사 예시','“바쁜 업무 중에도 함께 도와주셔서 고마워요.”<br>등록·공유 기능은 후속 구현 예정입니다.');return}
if(b.dataset.sos){document.getElementById('sosresult').innerHTML=card(b.dataset.sos,'연결 준비 중입니다. 실제 기관정보와 검증된 안내자료를 확인한 뒤 연결합니다. 응급상황이라면 119 신고를 우선하세요.');return}
if(b.dataset.ai){const k=b.dataset.ai;document.getElementById('answer').innerHTML=`<div class="bubble">${names[k]} 메뉴에서 필요한 정보를 찾아볼 수 있어요.<button class="btn" data-go="${k}">${names[k]} 열기</button></div>`;return}
if(b.id==='care-next'){careStep=(careStep+1)%4;render();return}if(b.id==='care-reset'){careStep=0;render();return}
});
