const guideSource=`<div class="card"><p class="meta">출처: 국민건강보험공단 「2026년 건강검진 안내」 2, 5~9쪽. 일반검진의 생애주기 기준이며 LX A/B/C형 추가 항목과 구분됩니다.</p><a class="btn secondary" href="assets/2026-checkup-guide.pdf" target="_blank" rel="noopener">2026년 원문 안내문 보기</a></div>`;
const guideBack=`<button class="btn secondary" data-go="checkup">검진기관 찾기로 돌아가기</button>`;
function prepareView(){return head('검진 전 체크리스트')+`<p class="lead">예약한 병원의 개별 안내를 우선 확인하세요. 체크 상태는 저장되지 않습니다.</p>`+[
['예약·방문시간 확인','병원 예약시간과 접수시간을 확인하고 방문하세요.'],
['금식 안내 확인','공단 안내: 전날 저녁 9시 이후 금식, 당일 아침 음식·물·커피·우유·담배·주스·껌 등을 삼가세요. 오후 검진은 최소 8시간 이상 공복을 유지하도록 안내하고 있습니다. 병원의 검사별 지침을 우선 따르세요.'],
['문진표 미리 준비','문진표는 본인이 작성하세요. 비대면 문진표를 미리 작성하면 검진시간을 줄일 수 있습니다.'],
['약 복용·내시경 준비 확인','복용약, 대장내시경 장정결, 수면내시경 등 개별 준비사항은 예약 병원에 확인하세요. 약을 임의로 중단하지 마세요.'],
['자궁경부암 검사 준비','공단 안내: 생리기간을 피하고 검사 전 2~3일은 질 세척 등을 피하도록 안내합니다. 자세한 준비사항은 원문과 병원 안내를 확인하세요.'],
['당일 준비물 확인','병원이 안내한 신분증·검체·문진표 등 준비물과 이동계획을 확인하세요.']
].map(([t,d])=>`<div class="card"><label style="display:flex;align-items:start;gap:10px"><input type="checkbox" style="margin-top:6px;width:20px;height:20px"><div><h3>${t}</h3><p class="small">${d}</p></div></label></div>`).join('')+guideSource+guideBack;}
function ageView(){return head('나이별 검진 가이드')+`<p class="lead">연령과 성별을 선택하면 관련 검진 기준을 보여드려요. 선택값은 저장·전송되지 않습니다.</p><div class="fields card"><label>연령(세)<select id="guide-age"><option value="">선택하세요</option>${Array.from({length:81},(_,i)=>i+20).map(a=>`<option value="${a}">${a}세</option>`).join('')}</select></label><label>성별<select id="guide-sex"><option value="">선택하세요</option><option value="female">여성</option><option value="male">남성</option></select></label><button class="btn" id="guide-show">관련 검진 기준 보기</button></div><div id="guide-result" aria-live="polite"></div><div class="notice">해당 연령의 안내 기준입니다. 올해의 개인 검진 대상 여부나 검사 필요성을 판정하지 않습니다. 간암·폐암은 별도의 고위험군 조건이 필요합니다.</div>`+guideSource+guideBack;}
function ageItems(age,sex){let general=[];if(age>=(sex==='male'?24:40))general.push(['이상지질혈증 검사',`남성 24세 이상·여성 40세 이상, 4년 주기. ${sex==='male'?'24·28·32…':'40·44·48…'}세 기준.`]);if(age===40)general.push(['B형간염 검사','40세 · 면역자·보균자는 제외']);if(age===56)general.push(['C형간염 검사','56세']);if([54,60,66].includes(age)&&sex==='female')general.push(['골밀도 검사','54·60·66세 여성']);if([56,66].includes(age))general.push(['폐기능 검사','56·66세 · 2026년 신규 생애주기 항목']);if(age>=66)general.push(['인지기능장애 검사','66세 이상, 2년 주기(66·68·70…세)']);if(age<=79)general.push(['정신건강 검사(우울증)',age<=34?'20~34세: 2년 주기':'35~39세: 해당 연령 구간에서 1회 / 40~79세: 10년 단위 연령 구간에서 1회']);if(age<=34)general.push(['정신건강 검사(조기정신증)','20~34세: 2년 주기']);if([40,50,60,70].includes(age))general.push(['생활습관 평가','40·50·60·70세']);if([66,70,80].includes(age))general.push(['노인신체기능 검사','66·70·80세']);if(age===40)general.push(['치면세균막 검사','40세 · 구강검진 항목']);
let cancers=[];if(age>=40)cancers.push(['위암','40세 이상 · 2년마다 위내시경. 위내시경이 어려운 경우 위장조영검사.']);if(age>=50)cancers.push(['대장암','50세 이상 · 매년 분변잠혈검사. 양성인 경우 대장내시경.']);if(sex==='female'&&age>=40)cancers.push(['유방암','40세 이상 여성 · 2년마다 유방촬영']);if(sex==='female'&&age>=20)cancers.push(['자궁경부암','20세 이상 여성 · 2년마다 자궁경부세포검사']);if(age>=40)cancers.push(['간암 · 고위험군만','40세 이상 간암 고위험군 · 6개월마다 간초음파·혈청 알파태아단백검사. 간경변증, B형간염 항원 양성, C형간염 항체 양성, B형·C형 간염 바이러스에 의한 만성 간질환 등 조건 확인 필요.']);if(age>=54&&age<=74)cancers.push(['폐암 · 고위험군만','54~74세 고위험군 · 2년마다 저선량 흉부 CT. 30갑년 이상의 흡연력을 가진 현재 흡연자 등 별도 대상 조건 확인 필요.']);return {general,cancers};}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='guide-show'){const age=Number(document.getElementById('guide-age').value),sex=document.getElementById('guide-sex').value;const out=document.getElementById('guide-result');if(!age||!sex){out.innerHTML='<div class="notice">연령과 성별을 모두 선택하세요.</div>';return}const {general,cancers}=ageItems(age,sex);out.innerHTML=`<h2>${age}세 · ${sex==='female'?'여성':'남성'} 관련 기준</h2><div class="card"><h3>일반검진 공통항목</h3><p class="small">신체계측, 시력·청력, 혈압, 공복혈당, 간기능·신장기능, 혈색소, 요검사, 흉부방사선, 구강검진 등</p></div><h2>성·연령별 일반검진</h2>${general.map(([t,d])=>card(t,d)).join('')}<h2>암검진 기준</h2>${cancers.length?cancers.map(([t,d])=>card(t,d)).join(''):'<div class="card"><p class="small">선택한 연령·성별에 해당하는 국가암검진 연령 기준은 없습니다. 개인별 검사 필요성은 별도 상담으로 확인하세요.</p></div>'}<p class="meta">LX 종합검진의 유형별 항목·선택검사는 별도로 확인할 수 있습니다.</p><button class="btn" data-go="checkup">A/B/C형 항목 살펴보기</button>`;}});
