let climateSeason=(new Date().getMonth()>=4&&new Date().getMonth()<=8)?'summer':'winter';
const climateSource='https://data.kma.go.kr/climate/windChill/selectWindChillChart.do';
const healthClimateSource='https://health.kdca.go.kr/healthhazard/clmtInfo/heatWaveInfo?subtab=warmHeat&tab=heat';
function summerFeels(t,rh){const tw=t*Math.atan(.151977*Math.sqrt(rh+8.313659))+Math.atan(t+rh)-Math.atan(rh-1.67633)+.00391838*Math.pow(rh,1.5)*Math.atan(.023101*rh)-4.686035;return -.2442+.55399*tw+.45535*t-.0022*tw*tw+.00278*tw*t+3}
function winterFeels(t,ms){const v=Math.pow(ms*3.6,.16);return 13.12+.6215*t-11.37*v+.3965*v*t}
function climate(){const summer=climateSeason==='summer';return head('폭염·한파 건강관리')+`<div class="chips"><button class="chip ${summer?'active':''}" data-climate-season="summer">여름 · 온열질환</button><button class="chip ${!summer?'active':''}" data-climate-season="winter">겨울 · 한랭질환</button></div><a class="btn secondary" href="https://www.weather.go.kr/w/index.do">기상청 날씨·체감온도·특보 확인</a><p class="meta">기상청에서 지역을 선택하세요. 지역 날씨와 실제 작업장 환경은 다를 수 있습니다.</p><section class="card"><h2>현장 체감온도 계산</h2><p class="small">휴대폰이 직접 측정하지 않습니다. 현장에서 측정한 값을 입력하세요. 입력값은 저장·전송하지 않습니다.</p><form id="climate-form"><label class="climate-field">기온 (℃)<input type="number" id="climate-temp" step="any" min="${summer?'0':'-80'}" max="${summer?'50':'10'}" required inputmode="decimal" placeholder="측정 기온"></label><label class="climate-field">${summer?'상대습도 (%)':'10분 평균 풍속 (m/s)'}<input type="number" id="climate-other" step="any" min="${summer?'5':'1.3'}" max="${summer?'99':'100'}" required inputmode="decimal" placeholder="${summer?'측정 습도':'측정 평균 풍속'}"></label><p class="meta">${summer?'여름 계산 입력 범위: 기온 0~50℃ · 습도 5~99%. 범위를 벗어나면 공식 자료를 확인하세요.':'겨울 계산 조건: 기온 10℃ 이하 · 풍속 1.3m/s 이상. 순간풍속 대신 10분 평균값을 사용하세요.'}</p><button class="btn" type="submit">체감온도 계산</button></form><div id="climate-result" role="status" aria-live="polite"></div><p class="meta">기상청 공개 산출식 기반 참고 계산값입니다. 일 최고·최저값이나 공식 특보가 아닙니다. 일사·복사열·작업강도·복장을 모두 반영하지 않습니다.</p><a class="textbtn" href="${climateSource}">계산식·공식 자료 확인</a></section><section class="card"><h2>작업 전 체크</h2>${(summer?['마실 물과 시원한 휴식 장소 확인','작업·휴식 계획과 현장 예방수칙 확인','동료의 상태와 비상연락 경로 확인']:['방한복·장갑·모자와 마른 여벌 준비','따뜻한 휴식 장소와 작업·휴식 계획 확인','동료의 상태와 비상연락 경로 확인']).map(t=>`<label class="climate-check"><input type="checkbox"> ${t}</label>`).join('')}</section><section class="card" id="climate-care"><h2>${summer?'온열질환':'한랭질환'} · 증상과 대응</h2><p>${summer?'두통·어지럼·근육경련·극심한 피로가 생기면 작업을 멈추고 시원한 곳으로 이동하세요.':'심한 떨림·말이 어눌해짐·판단력 저하, 피부 감각 저하 등의 증상을 살펴보세요.'}</p><p>${summer?'의식이 떨어지거나 열사병이 의심되면 즉시 119에 신고하고, 옷을 느슨하게 해 몸을 식히세요.':'저체온증이 의심되거나 의식이 떨어지면 119에 신고하세요. 따뜻한 곳으로 옮기고 젖은 옷을 벗겨 담요로 감싸세요.'}</p><p>${summer?'의식이 없는 사람에게는 물이나 음료를 주지 마세요.':'동상 부위를 문지르거나 뜨거운 열을 직접 대지 마세요. 의식이 없는 사람에게 음료를 주지 마세요.'}</p><a class="btn secondary" href="${healthClimateSource}">질병관리청 예방·응급조치 자세히 보기</a></section><a class="btn danger" href="tel:119">119 전화 연결</a><a class="btn secondary" href="https://sos.lx.or.kr/">LX SOS 연결</a><button class="btn secondary" data-go="sos">응급·SOS 메뉴로</button>`}
const climateBaseRender=render;render=function(){if(page==='climate'){view.innerHTML=climate();nav.innerHTML='';return}climateBaseRender()};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.climateSeason){climateSeason=b.dataset.climateSeason;render()}if(b?.dataset.climateOpen){climateSeason=b.dataset.climateOpen;go('climate');e.stopImmediatePropagation()}},true);
document.addEventListener('submit',e=>{if(e.target.id!=='climate-form')return;e.preventDefault();const t=Number(document.getElementById('climate-temp').value),n=Number(document.getElementById('climate-other').value),out=document.getElementById('climate-result'),summer=climateSeason==='summer';if(!e.target.checkValidity()||!Number.isFinite(t)||!Number.isFinite(n)){out.textContent='입력 범위와 단위를 확인하세요.';return}const val=summer?summerFeels(t,n):winterFeels(t,n);out.innerHTML=`<div class="notice" style="margin-top:16px"><span class="tag">현장 입력값 기준 · 참고 계산</span><h2 style="font-size:32px;margin:8px 0">${val.toFixed(1)}℃</h2><p class="small">기온 ${t}℃ · ${summer?'습도 '+n+'%':'풍속 '+n+'m/s'}<br>계산 시각 ${new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',dateStyle:'short',timeStyle:'short'}).format(new Date())}</p><a class="textbtn" href="#climate-care">${summer?'온열질환':'한랭질환'} 증상·대응 확인</a></div>`});
