// Source-backed pre-checkup navigator. No personal results or live AI requests.
const examGuides=[
{id:'stomach',name:'위내시경',match:n=>/내시경/.test(n)&&/위 \(/.test(n),summary:'식도·위·십이지장 안쪽을 카메라로 직접 살펴보는 검사예요.',purpose:'식도염, 위궤양 등 소화관의 이상을 살펴보고, 필요한 경우 조직을 채취해 확인합니다.',method:'입으로 가느다란 내시경을 넣습니다. 진정제 사용 여부는 병원 안내에 따라 결정합니다.',prepare:'금식 시간과 복용약은 예약 병원에 확인하세요. 진정제를 사용하는 경우 보호자 동행과 검사 후 휴식이 필요합니다.',limit:'검사 결과 해석과 추가 조직검사 필요 여부는 의료진이 판단합니다. 수면 여부와 관련 비용은 병원별로 다를 수 있습니다.',source:'질병관리청 · 위내시경',url:'https://health.kdca.go.kr/healthinfo/biz/health/gnrlzHealthInfo/gnrlzHealthInfo/gnrlzHealthInfoView.do?cntnts_sn=5258'},
{id:'colon',name:'대장내시경',match:n=>/내시경/.test(n)&&/대장 \(/.test(n),summary:'대장 안쪽을 살펴보고 용종 등 병변을 확인하는 검사예요.',purpose:'대장 점막의 용종과 병변을 살펴봅니다. 용종 발견 시 제거 여부와 후속 검사 시기는 의료진이 판단합니다.',method:'항문으로 내시경을 넣어 대장 내부를 관찰합니다.',prepare:'장 청소와 식사 조절에 대한 예약 병원의 안내를 확인하세요. 복용약과 진정제 사용, 보호자 동행 여부도 확인합니다.',limit:'용종 제거·조직검사 비용이 검진비에 포함되는지는 별도 확인해야 합니다. 검사 주기는 이전 검사 소견에 따라 달라질 수 있습니다.',source:'질병관리청 · 대장용종',url:'https://health.kdca.go.kr/healthinfo/biz/health/gnrlzHealthInfo/gnrlzHealthInfo/gnrlzHealthInfoView.do?cntnts_sn=6531'},
{id:'abdomen',name:'복부초음파',match:n=>/초음파/.test(n)&&/복부/.test(n),summary:'초음파로 간과 담낭 등 복부 장기의 모습을 살펴보는 검사예요.',purpose:'상복부 검사에서는 간, 담낭, 담도, 췌장, 비장의 병변이나 결석 등을 살펴봅니다. 병원 항목표의 검사 범위는 확인이 필요합니다.',method:'배에 젤을 바르고 탐촉자를 움직이며 영상을 봅니다. 검사 중 숨을 들이마시거나 참도록 안내할 수 있습니다.',prepare:'금식 여부·시간과 복용약 안내는 예약 병원에 확인하세요.',limit:'상복부·하복부 등 검사 범위가 다를 수 있으므로 ‘복부’라는 이름만으로 같은 검사로 판단하지 않습니다.',source:'서울아산병원 · 상복부 초음파 검사',url:'https://www.amc.seoul.kr/asan/examination/examView.do?examId=32976'},
{id:'ct',name:'CT',match:n=>/^CT\s*·/i.test(n),summary:'엑스선으로 몸의 단면 영상을 만드는 검사예요.',purpose:'촬영 부위의 장기와 조직을 살펴봅니다. 뇌·흉부·복부 등 촬영 부위와 방법에 따라 확인하는 내용이 달라집니다.',method:'촬영 장비 안에서 누운 상태로 검사합니다. 검사 목적에 따라 조영제를 사용할 수 있습니다.',prepare:'임신 가능성, 조영제 반응 경험과 복용약 등은 병원에 미리 알리세요. 금식 등 준비사항은 촬영 방법별 안내를 따릅니다.',limit:'방사선 노출이 있습니다. CT를 많이 받는 것이 더 좋은 검진을 의미하지 않으며, 검사 필요성은 의료진과 확인합니다.',source:'ACR·RSNA RadiologyInfo · Body CT (영문)',url:'https://www.radiologyinfo.org/en/info/bodyct'},
{id:'mri',name:'MRI',match:n=>/^MRI\s*·/i.test(n),summary:'자기장과 전파를 이용해 몸 안의 조직을 영상으로 보는 검사예요.',purpose:'뇌와 척추 등 촬영 부위의 조직을 살펴봅니다. 부위·촬영 방식에 따라 확인 범위가 다릅니다.',method:'장비 안에 누워 촬영하며, 검사 중 큰 소리가 날 수 있습니다. 일부 검사는 조영제를 사용합니다.',prepare:'심박동기 등 삽입 장치나 몸속 금속, 임신 가능성과 조영제 반응 경험을 병원에 알리세요. 좁은 공간이 어렵다면 사전에 문의합니다.',limit:'엑스선을 사용하는 CT와 검사 원리가 다릅니다. MRI가 모든 상황에서 CT보다 우수한 것은 아니며, MRA와도 같은 이름으로 간주하지 않습니다.',source:'ACR·RSNA RadiologyInfo · Body MRI (영문)',url:'https://www.radiologyinfo.org/en/info/bodymr'}
];
let examGuideType='C',examGuideRegion='전체';
function guideForItem(name){return examGuides.find(g=>g.match(name))}
function examGuideHome(){view.innerHTML=head('검진항목 쉽게 알기')+`<p class="exam-intro">검진표의 어려운 이름, 선택 전에 알아보세요.</p><div class="notice">개인 검진 결과 없이 이용하는 검진 전 안내입니다.</div><div class="fields"><label>검사 이름 찾기<input id="guide-query" placeholder="예: 위내시경, 복부초음파, CT" autocomplete="off"></label></div><div id="guide-list">${examGuideList('')}</div><button class="btn secondary" data-guide-difference="1">CT와 MRI는 어떻게 다를까요?</button><p class="small exam-demo">설명 도우미 DEMO · 출처 기반 안내<br>현재 실시간 생성형 AI는 연결되어 있지 않습니다.</p><button class="btn secondary" data-go="checkup">검진기관 찾기로</button>`;window.scrollTo(0,0)}
function examGuideList(query){const q=query.toLowerCase().replace(/\s/g,'');const gs=examGuides.filter(g=>(g.name+g.summary).toLowerCase().replace(/\s/g,'').includes(q));return gs.map(g=>`<button class="exam-guide-option" data-exam-guide="${g.id}"><strong>${g.name}</strong><span>${g.summary}</span></button>`).join('')||'<div class="empty">아직 설명이 준비되지 않은 검사예요. 등록된 검사명을 검색하거나 병원에 문의하세요.</div>'}
function examGuideDetail(id){const g=examGuides.find(g=>g.id===id);if(!g)return;view.innerHTML=head('검진항목 쉽게 알기')+`<div class="exam-detail"><span class="tag">검진 전 안내</span><h2>${g.name}</h2><p class="exam-summary">${g.summary}</p>${[['무엇을 살펴보나요?',g.purpose],['어떻게 검사하나요?',g.method],['미리 확인할 준비사항',g.prepare],['선택할 때 알아둘 점',g.limit]].map(([h,t])=>`<section class="card"><h3>${h}</h3><p>${t}</p></section>`).join('')}<details class="card"><summary>병원에 물어볼 질문</summary><ul><li>제 검진유형에 포함되어 있나요?</li><li>선택검사라면 같은 묶음에서 몇 개를 고르나요?</li><li>검사 범위와 별도 비용은 어떻게 되나요?</li><li>금식·복용약 등 준비 안내를 받을 수 있나요?</li></ul></details><a class="exam-source" href="${g.url}" target="_blank" rel="noopener">출처: ${g.source} · 원문 보기</a><p class="small">설명 확인일 2026.10.07 · 일반적인 검사 설명입니다. 개인별 검사 필요성과 결과는 의료진에게 확인하세요.</p><h2 class="exam-hospital-heading">이 검사를 제공하는 기관</h2><div class="fields"><label>지역<select id="guide-region"><option>전체</option>${[...new Set(hospitalData.map(h=>h.region))].map(r=>`<option ${r===examGuideRegion?'selected':''}>${esc(r)}</option>`).join('')}</select></label><label>검진유형<select id="guide-type">${['C','B','A'].map(t=>`<option value="${t}" ${t===examGuideType?'selected':''}>${t}형 · ${t==='C'?'166,000':t==='B'?'266,000':'366,000'}원</option>`).join('')}</select></label></div><p class="small">항목표가 연결된 KMI 3개 기관에서만 조회합니다. CT·MRI는 촬영 부위별로 확인하세요.</p><div id="guide-hospitals">${guideHospitals(g)}</div><button class="btn secondary" data-guide-home="1">다른 검사 알아보기</button><button class="btn secondary" data-go="checkup">검진기관 찾기로</button></div>`;view.dataset.guide=id;window.scrollTo(0,0)}
function guideHospitals(g){const hs=hospitalData.filter(h=>examGuideRegion==='전체'||h.region===examGuideRegion).map(h=>({h,items:h.items.filter(i=>g.match(i.name)&&['기본 포함','선택 가능'].includes(i.types[examGuideType].status))})).filter(v=>v.items.length);return hs.map(({h,items})=>`<div class="card"><h3>${esc(h.name)}</h3><p class="small">${esc(h.region)} · ${examGuideType}형</p>${items.map(i=>`<div class="exam-match"><strong>${esc(i.name)}</strong><span>${esc(i.types[examGuideType].status)} · 원문 ${esc(i.types[examGuideType].raw)}</span></div>`).join('')}<p class="small">선택 묶음·추가 비용은 원본 안내와 병원 확인이 필요합니다.</p><button class="btn secondary" data-hospital="${h.id}">전체 항목표 확인</button></div>`).join('')||'<div class="empty">연결된 항목표에서 해당 조건을 확인하지 못했습니다. 다른 기관의 제공 여부는 아직 미확인입니다.</div>'}
const guideCheckupBase=checkup;checkup=function(){return guideCheckupBase().replace('<div class="fields">','<button class="exam-entry" data-guide-home="1"><strong>검진항목 쉽게 알기</strong><span>검사 설명을 보고, 제공 기관까지 찾아보세요.</span></button><div class="fields">')};
const guideItemTableBase=itemTable;itemTable=function(h){let html=guideItemTableBase(h);h.items.forEach(i=>{const g=guideForItem(i.name);if(g)html=html.replace(`${esc(i.name)}<div class="meta">`,`${esc(i.name)}<button class="exam-inline" data-exam-guide="${g.id}" aria-label="${esc(i.name)} 쉽게 알아보기">쉽게 알아보기</button><div class="meta">`)});return html};
document.addEventListener('input',e=>{if(e.target.id==='guide-query')document.getElementById('guide-list').innerHTML=examGuideList(e.target.value)});
document.addEventListener('change',e=>{if(['guide-region','guide-type'].includes(e.target.id)){examGuideRegion=document.getElementById('guide-region').value;examGuideType=document.getElementById('guide-type').value;const g=examGuides.find(g=>g.id===view.dataset.guide);if(g)document.getElementById('guide-hospitals').innerHTML=guideHospitals(g)}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.guideHome||b.dataset.examGuide||b.dataset.guideDifference){e.stopImmediatePropagation();if(b.dataset.guideHome)examGuideHome();else if(b.dataset.examGuide)examGuideDetail(b.dataset.examGuide);else {view.innerHTML=head('CT와 MRI 차이')+`<p class="exam-intro">검사 원리와 확인하는 내용이 달라요.</p><div class="card"><h2>CT</h2><p>엑스선으로 단면 영상을 만듭니다. 방사선 노출이 있으며 검사에 따라 조영제를 사용합니다.</p><button class="btn secondary" data-exam-guide="ct">CT 자세히 알기</button></div><div class="card"><h2>MRI</h2><p>자기장과 전파로 영상을 만듭니다. 엑스선을 사용하지 않으며 몸속 금속·삽입 장치의 확인이 중요합니다.</p><button class="btn secondary" data-exam-guide="mri">MRI 자세히 알기</button></div><div class="notice">어느 검사가 더 좋은지는 촬영 부위와 검사 목적에 따라 달라집니다. 서로 자동으로 대체할 수 있는 검사로 보지 않습니다.</div><button class="btn secondary" data-guide-home="1">검사 목록으로</button>`;window.scrollTo(0,0)}}},true);
