const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let selectedHospitals=new Set(),activeType='C';
function showHospitals(){const region=document.getElementById('real-region').value;activeType=document.getElementById('real-type').value;const exam=document.getElementById('real-exam').value.trim();const matches=hospitalData.filter(h=>(region==='전체'||h.region===region)&&(!exam||h.items.some(i=>i.name.toLowerCase().includes(exam.toLowerCase())&&['기본 포함','선택 가능'].includes(i.types[activeType].status))));document.getElementById('real-results').innerHTML=`<p class="small">${matches.length}개 기관 · ${activeType}형 기준</p>`+matches.map(h=>`<div class="card"><span class="tag">${esc(h.region)}</span><h3 style="margin-top:10px">${esc(h.name)}</h3><p class="small">${esc(h.address).replace(/\n/g,'<br>')}</p><p class="small">전화: ${esc(h.phone)}${h.phoneCheck?' · 번호 확인 필요':''}</p>${h.phoneCheck?'':`<a class="btn secondary" href="tel:${(h.phone.match(/\d[\d-]+/)||[''])[0]}">전화 앱 열기</a>`}<p class="meta">${h.items.length?'유형별 요약 항목 연결 · 선택조건 원문 확인 필요':'검사 항목 구조화 예정'}</p>${h.note?`<details><summary class="small">2026년 안내사항</summary><p class="small">${esc(h.note).replace(/\n/g,'<br>')}</p><p class="meta">제공 자료의 안내이며 현재 예약 가능 여부는 기관에 확인하세요.</p></details>`:''}<button class="btn secondary" data-hospital="${h.id}">유형별 항목 보기</button><label class="small"><input type="checkbox" name="real-pick" value="${h.id}" ${selectedHospitals.has(h.id)?'checked':''}> 비교에 담기</label></div>`).join('')+(matches.length?'':'<div class="empty">일치하는 기관이 없습니다. 관심검사 조건을 지우거나 지역을 넓혀보세요.</div>');}
function hospitalDetail(id){const h=hospitalData.find(h=>h.id===id);if(!h)return false;view.innerHTML=head(esc(h.name))+`<div class="notice">C형 166,000원 · B형 266,000원 · A형 366,000원<br>2026년 제공 제안서 요약표 원문 기준</div><p class="small">선택 코드·성별 제한·수면비 등은 기관 확인이 필요합니다. 미기재와 0은 포함으로 간주하지 않습니다.</p>`+itemTable(h);window.scrollTo(0,0);return true;}
document.addEventListener('change',e=>{if(e.target.name==='real-pick'){if(e.target.checked)selectedHospitals.add(e.target.value);else selectedHospitals.delete(e.target.value)} });
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
if(b.id==='real-search'){showHospitals()}
if(b.id==='real-compare'){const hs=hospitalData.filter(h=>selectedHospitals.has(h.id));document.getElementById('real-comparison').innerHTML=hs.length<2?'<div class="notice">기관을 2곳 이상 선택하세요.</div>':`<h2 style="margin-top:20px">${activeType}형 · 선택 기관 비교</h2><p class="small">검사 명칭은 각 제안서 원문을 유지했습니다. 같은 이름처럼 보여도 범위가 다를 수 있습니다.</p>`+hs.map(h=>`<div class="card"><h3>${esc(h.name)}</h3><p class="small">${esc(h.region)} · ${esc(h.phone)}</p>${h.items.length?h.items.map(i=>`<div class="small" style="padding:7px 0;border-bottom:1px solid var(--line)">${esc(i.name)}<br><b>${esc(i.types[activeType].status)}</b> · ${esc(i.types[activeType].raw)}</div>`).join(''):'<p class="small">항목표 구조화 예정 · 포함 여부 미확인</p>'}</div>`).join('')}
});
