let programMonth='2026-10',programDay='',programMode='list';
const programToday=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date());
function programStatus(p){const t=programToday();if(p.cycle==='상시')return t<=p.end?'상시 운영':'운영 종료';if(p.close)return t<p.open?'신청 예정':t<=p.close?'신청 기간':t>p.end?'진행일 경과':t>=p.start?'신청 마감 · 진행 기간':'신청 마감 · 진행 예정';return p.id==='camp'?'회차별 접수 확인':'일정 예정'}
const visiblePrograms=()=>realPrograms.filter(p=>p.scope!=='본사'||org==='본사');
function shortProgramDate(date){return date.slice(5).replace('-','/')}
function programFacts(p){if(p.id==='clinic')return [['일정','10/15 · 10/29 · 11/12 · 11/26'],['시간','오후 2–4시 · 예정']];if(p.id==='camp')return [['회차','10/12–16 · 11/9–13 · 12/7–11'],['기간','회차별 4박 5일']];if(p.id==='follow')return [['일정','9–11월 부서별 상담 · 예정'],['시간·장소','추후 안내']];if(p.id==='eap')return [['대상','LX 및 LX 협력사 전 직원'],['운영','~ 12/04 · 상시']];return [['신청',shortProgramDate(p.open)+'–'+shortProgramDate(p.close)],['운영',shortProgramDate(p.start)+(p.end!==p.start?'–'+shortProgramDate(p.end):'')+(p.time?' · '+p.time:'')]]}
function programPreview(p){const active=p.close&&programToday()>=p.open&&programToday()<=p.close;return `<button class="program-preview ${active?'recruiting':''}" data-real-program="${p.id}"><div class="program-badges"><span class="program-scope">${p.scope}</span><span class="program-status ${active?'open':''}">${programStatus(p)}</span></div><h3>${p.title}</h3><dl>${programFacts(p).map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl><span class="program-detail-link">상세 안내 보기</span></button>`}
function programDetail(id){const p=realPrograms.find(p=>p.id===id);if(!p)return false;view.innerHTML=head('프로그램 안내')+`<span class="tag">${p.scope}</span><h2>${p.title}</h2><p class="lead">${programStatus(p)}</p>${card('참여 안내',p.text)}${card('신청·문의',p.apply)}${p.poster?`<details class="card"><summary>원본 안내문 보기</summary><img class="program-poster" src="assets/${p.poster}" alt="${p.title} 원본 안내문"></details>`:''}<button class="btn secondary" data-go="program">프로그램 목록으로</button>`;window.scrollTo(0,0);return true;}
program=function(){const ps=visiblePrograms(),es=programEvents.filter(e=>ps.some(p=>p.id===e.id)&&e.date.startsWith(programMonth));const [y,m]=programMonth.split('-').map(Number),offset=new Date(y,m-1,1).getDay(),days=new Date(y,m,0).getDate();const ordered=[...ps].sort((a,b)=>Number(Boolean(b.close&&programToday()>=b.open&&programToday()<=b.close))-Number(Boolean(a.close&&programToday()>=a.open&&programToday()<=a.close)));return head('건강프로그램')+`<div class="sectionhead program-heading"><h2>나에게 맞는 건강활동</h2><div class="org">${orgSelect()}</div></div><div class="program-tabs" role="group" aria-label="프로그램 보기 방식"><button data-program-mode="list" aria-pressed="${programMode==='list'}" class="${programMode==='list'?'active':''}">프로그램</button><button data-program-mode="calendar" aria-pressed="${programMode==='calendar'}" class="${programMode==='calendar'?'active':''}">월별 일정</button></div>${programMode==='list'?`<div class="program-list">${ordered.map(programPreview).join('')}</div>`:`<div class="program-calendar-panel"><div class="row"><button class="btn secondary" data-month="-1" aria-label="이전 달">이전</button><h2>${y}년 ${m}월</h2><button class="btn secondary" data-month="1" aria-label="다음 달">다음</button></div><div class="program-calendar">${['일','월','화','수','목','금','토'].map(d=>`<span class="weekday">${d}</span>`).join('')}${'<span></span>'.repeat(offset)}${Array.from({length:days},(_,i)=>{const date=programMonth+'-'+String(i+1).padStart(2,'0'),events=es.filter(e=>e.date===date);return `<button class="calendar-day ${date===programDay?'selected':''}" data-date="${date}" aria-label="${date}, 일정 ${events.length}개" ${date===programDay?'aria-pressed="true"':''}>${i+1}<span class="calendar-marks">${[...new Set(events.map(e=>e.id))].map(id=>`<i class="mark-${id}"></i>`).join('')}</span></button>`}).join('')}</div><p class="small">민트: 집중관리 · 보라: 힐링 · 주황: 금연캠프 · 파랑: 본사 클리닉 · 분홍: 사후관리</p><div class="sectionhead"><h2>${programDay&&programDay.startsWith(programMonth)?programDay.slice(5).replace('-','/')+' 일정':'이달의 일정'}</h2>${programDay?'<button class="textbtn" data-all-dates="1">전체 보기</button>':''}</div>${es.filter(e=>!programDay||e.date===programDay).sort((a,b)=>a.date.localeCompare(b.date)).map(e=>`<button class="event-card" data-real-program="${e.id}"><b>${e.date.slice(5).replace('-','/')} · ${ps.find(p=>p.id===e.id).title}</b><span>${e.label}</span></button>`).join('')||'<div class="empty">등록된 일정이 없습니다.</div>'}</div>`}<p class="program-source">제공된 2026년 안내문 기준 · 일정은 변경될 수 있습니다.</p>${org!=='본사'?'<p class="small">본사를 선택하면 본사 클리닉·사후관리 일정도 볼 수 있어요.</p>':''}`};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.programMode){programMode=b.dataset.programMode;programDay='';render()}if(b.dataset.month){const [y,m]=programMonth.split('-').map(Number),d=new Date(y,m-1+Number(b.dataset.month),1);programMonth=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');programDay='';render()}if(b.dataset.date){programDay=b.dataset.date;render()}if(b.dataset.allDates){programDay='';render()}});
