let programMonth='2026-10',programDay='',programMode='list';
const realPrograms=[
{id:'chronic',title:'혈압·혈당 6주 집중관리',scope:'전사',start:'2026-10-19',end:'2026-11-29',open:'2026-10-07',close:'2026-10-14',text:'혈압 낮춰랍 / 혈당 웃는당 · 각 30명. 두 과정 중 하나를 신청하세요. 신청 후 선정 결과는 10/16 개별 카카오 알림으로 안내됩니다.',apply:'어떠케어 앱에서 팝업의 신청하기를 선택하세요. 안내문 QR은 앱 설치용입니다.',poster:'chronic-care.jpg'},
{id:'healing',title:'EAP 힐링 · 모루인형 만들기',scope:'전사',start:'2026-10-28',end:'2026-10-28',open:'2026-10-01',close:'2026-10-02',time:'20:00–21:30',text:'ZOOM 온라인 참여 · 강사 김하윤. 선정자 15명에게 재료를 자택 배송하며, 접속 링크와 주소 확인은 개별 메일·문자로 안내됩니다.',apply:'안내문 QR의 구글폼으로 신청 · 문의 070-4888-3600',poster:'eap-october.jpg'},
{id:'camp',title:'전문치료형 금연캠프',scope:'외부 연계',start:'2026-10-12',end:'2026-12-11',text:'4박 5일 전문치료형 프로그램 · 전북금연지원센터. 10차 10/12–16, 11차 11/9–13, 12차 12/7–11. 회차별 접수 가능 여부와 장소는 센터에 확인하세요. 일정은 안내문 기준이며 변경될 수 있습니다.',apply:'안내문 QR로 신청 후 담당자 안내 · 문의 063-859-2402. 환급형 예치금 등 참여 조건은 안내문을 확인하세요.',poster:'quit-camp.jpg'},
{id:'clinic',title:'본사 금연클리닉',scope:'본사',start:'2026-10-15',end:'2026-11-26',time:'14:00–16:00',text:'예정 일정: 10/15, 10/29, 11/12, 11/26 · 오후 2–4시. 장소와 참여 방법은 추후 안내됩니다.',apply:'본사 보건관리자 안내를 확인하세요.'},
{id:'follow',title:'본사 건강검진 사후관리',scope:'본사',start:'2026-09-09',end:'2026-11-25',text:'부서별 상담 일정(예정)입니다. 날짜를 선택해 대상 부서를 확인하세요. 시간·장소는 추후 안내됩니다.',apply:'11/25 미참여자 추가상담 및 비대면 상담'}];
const programEvents=[];
function pe(date,id,label){programEvents.push({date,id,label})}
pe('2026-10-02','healing','신청 마감');pe('2026-10-28','healing','온라인 힐링 20:00–21:30');pe('2026-10-07','chronic','신청 시작');pe('2026-10-14','chronic','신청 마감');pe('2026-10-16','chronic','선정 결과 안내');pe('2026-10-19','chronic','6주 관리 시작');pe('2026-11-29','chronic','6주 관리 종료');
[['10-12','10-16','10차'],['11-09','11-13','11차'],['12-07','12-11','12차']].forEach(([a,b,n])=>{for(let d=new Date('2026-'+a+'T12:00:00Z');d<=new Date('2026-'+b+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+1))pe(d.toISOString().slice(0,10),'camp',n+' 금연캠프 · 예정')});
['10-15','10-29','11-12','11-26'].forEach(d=>pe('2026-'+d,'clinic','금연클리닉 14:00–16:00 · 예정'));
[['09-09','홍보처, 안전보건처, 사업개발처'],['09-21','예산법무처, 경영성과처, 지적사업실, 지적재조사처'],['09-30','토지보상처, 고객지원처, 노동조합'],['10-14','공간정보실(공간사업기획처, 국토도시사업처)'],['10-21','디지털SOC처, 글로벌사업처'],['10-28','플랫폼사업처, 협력사'],['11-04','AI디지털전략실(AI혁신처, 정보보안운영처), LX고객센터, 협력사'],['11-11','인사처, 재무처, 노사협력처, 감사실'],['11-18','기획처, 경영지원실(운영지원처, 자산관리처, 비서실)'],['11-25','미참여자 추가상담 및 비대면 상담']].forEach(([d,t])=>pe('2026-'+d,'follow',t));
const programToday=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date());
function programStatus(p){const t=programToday();if(p.close)return t<p.open?'신청 예정':t<=p.close?'신청 기간':t>p.end?'진행일 경과':t>=p.start?'신청 마감 · 진행 기간':'신청 마감 · 진행 예정';return p.id==='camp'?'회차별 접수 확인':'일정 예정'}
const visiblePrograms=()=>realPrograms.filter(p=>p.scope!=='본사'||org==='본사');
function shortProgramDate(date){return date.slice(5).replace('-','/')}
function programFacts(p){if(p.id==='clinic')return [['일정','10/15 · 10/29 · 11/12 · 11/26'],['시간','오후 2–4시 · 예정']];if(p.id==='camp')return [['회차','10/12–16 · 11/9–13 · 12/7–11'],['기간','회차별 4박 5일']];if(p.id==='follow')return [['일정','9–11월 부서별 상담 · 예정'],['시간·장소','추후 안내']];return [['신청',shortProgramDate(p.open)+'–'+shortProgramDate(p.close)],['운영',shortProgramDate(p.start)+(p.end!==p.start?'–'+shortProgramDate(p.end):'')+(p.time?' · '+p.time:'')]]}
function programPreview(p){const active=p.close&&programToday()>=p.open&&programToday()<=p.close;return `<button class="program-preview ${active?'recruiting':''}" data-real-program="${p.id}"><div class="program-badges"><span class="program-scope">${p.scope}</span><span class="program-status ${active?'open':''}">${programStatus(p)}</span></div><h3>${p.title}</h3><dl>${programFacts(p).map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl><span class="program-detail-link">상세 안내 보기</span></button>`}
program=function(){const ps=visiblePrograms(),es=programEvents.filter(e=>ps.some(p=>p.id===e.id)&&e.date.startsWith(programMonth));const [y,m]=programMonth.split('-').map(Number),offset=new Date(y,m-1,1).getDay(),days=new Date(y,m,0).getDate();const ordered=[...ps].sort((a,b)=>Number(Boolean(b.close&&programToday()>=b.open&&programToday()<=b.close))-Number(Boolean(a.close&&programToday()>=a.open&&programToday()<=a.close)));return head('건강프로그램')+`<div class="sectionhead program-heading"><h2>나에게 맞는 건강활동</h2><div class="org">${orgSelect()}</div></div><div class="program-tabs" role="group" aria-label="프로그램 보기 방식"><button data-program-mode="list" aria-pressed="${programMode==='list'}" class="${programMode==='list'?'active':''}">프로그램</button><button data-program-mode="calendar" aria-pressed="${programMode==='calendar'}" class="${programMode==='calendar'?'active':''}">월별 일정</button></div>${programMode==='list'?`<div class="program-list">${ordered.map(programPreview).join('')}</div>`:`<div class="program-calendar-panel"><div class="row"><button class="btn secondary" data-month="-1" aria-label="이전 달">이전</button><h2>${y}년 ${m}월</h2><button class="btn secondary" data-month="1" aria-label="다음 달">다음</button></div><div class="program-calendar">${['일','월','화','수','목','금','토'].map(d=>`<span class="weekday">${d}</span>`).join('')}${'<span></span>'.repeat(offset)}${Array.from({length:days},(_,i)=>{const date=programMonth+'-'+String(i+1).padStart(2,'0'),events=es.filter(e=>e.date===date);return `<button class="calendar-day ${date===programDay?'selected':''}" data-date="${date}" aria-label="${date}, 일정 ${events.length}개" ${date===programDay?'aria-pressed="true"':''}>${i+1}<span class="calendar-marks">${[...new Set(events.map(e=>e.id))].map(id=>`<i class="mark-${id}"></i>`).join('')}</span></button>`}).join('')}</div><p class="small">민트: 집중관리 · 보라: 힐링 · 주황: 금연캠프 · 파랑: 본사 클리닉 · 분홍: 사후관리</p><div class="sectionhead"><h2>${programDay&&programDay.startsWith(programMonth)?programDay.slice(5).replace('-','/')+' 일정':'이달의 일정'}</h2>${programDay?'<button class="textbtn" data-all-dates="1">전체 보기</button>':''}</div>${es.filter(e=>!programDay||e.date===programDay).sort((a,b)=>a.date.localeCompare(b.date)).map(e=>`<button class="event-card" data-real-program="${e.id}"><b>${e.date.slice(5).replace('-','/')} · ${ps.find(p=>p.id===e.id).title}</b><span>${e.label}</span></button>`).join('')||'<div class="empty">등록된 일정이 없습니다.</div>'}</div>`}<p class="program-source">제공된 2026년 안내문 기준 · 일정은 변경될 수 있습니다.</p>${org!=='본사'?'<p class="small">본사를 선택하면 본사 클리닉·사후관리 일정도 볼 수 있어요.</p>':''}`};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.programMode){programMode=b.dataset.programMode;programDay='';render()}if(b.dataset.month){const [y,m]=programMonth.split('-').map(Number),d=new Date(y,m-1+Number(b.dataset.month),1);programMonth=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');programDay='';render()}if(b.dataset.date){programDay=b.dataset.date;render()}if(b.dataset.allDates){programDay='';render()}if(b.dataset.realProgram){const p=realPrograms.find(p=>p.id===b.dataset.realProgram);view.innerHTML=head('프로그램 안내')+`<span class="tag">${p.scope}</span><h2>${p.title}</h2><p class="lead">${programStatus(p)}</p>${card('참여 안내',p.text)}${card('신청·문의',p.apply)}${p.poster?`<details class="card"><summary>원본 안내문 보기</summary><img class="program-poster" src="assets/${p.poster}" alt="${p.title} 원본 안내문"></details>`:''}<button class="btn secondary" data-go="program">프로그램 목록으로</button>`}},true);
